### PR TITLE
iOS PR 1

### PR DESCRIPTION
**Pull request by yep**
Alright, using the workflow proposed in https://github.com/doublethinkco/cpp-ethereum-cross/issues/36#issuecomment-239047208, I'll create a pull request early.

On the one hand, this makes adding comments/requests for changes simpler, but on the other hand requires me to be more careful not to break existing functionality.

I'll put up some changes I would have used in a "private" branch up for discussion later.

For example, I'd like to change the download behavior in a way that I do not have to download the huge boost source tarball on every build.

Also, I'll probably add some comments on this PR to explain the rationale of some changes.

### CODE REVIEW

**Comment by bobsummerwill** [comment]
Thanks!

So the TravisCI breaks are exactly that Boost ZIP which I mentioned in the e-mail earlier, which I deleted not realizing it was used.

I will fix that up tomorrow, if I get a chance.

Yes - download is very crude.

**Comment by bobsummerwill** [comment]
OK - I got busy!

Just committed a change to switch to building against ethereum/cpp-ethereum and then let's see where we are sitting.

Do you think you have much more to do here before iOS supportg is in a mergeable state?

**Comment by bobsummerwill** [comment]
I just cherry-picked the Boost URL fix, btw.   Thanks!

**Comment by bobsummerwill** [comment]
Hey @yep!

So a year later I am intending to resume development on cpp-ethereum-cross.  Just for fun.

See https://twitter.com/BobSummerwill/status/942785956536446977

So I would like to see if I can get cpp-ethereum working on Samsung Gear S3, plus some variety of Apple Watch and Android Wear.

Not sure if you still care about getting cpp-ethereum working on iOS, but if you do it would be great to renew this collaboration.

I can update the cpp-ethereum version too.  The development team, led by @chriseth have it working for the latest Byzantium HF.

Still no Light Client support, but can avoid full sync by leveraging Parity's warp sync snapshots.

Might still need more storage or memory than we have available.  Any idea on min specs for memory / HD for cpp-ethereum, @chriseth, @chfast?

**Comment by bobsummerwill** [comment]
The latest cross-built binaries I released were for cpp-ethereum 1.2.2, the final Homestead release, in March 2016.

See https://github.com/doublethinkco/cpp-ethereum-cross/releases/tag/v1.2.2

To my understanding the cpp-ethereum client never really got the fixes required to get past the Shanghai attack blocks of mainnet (or if the fixes did work it was at the cost of processing those blocks so slowly, even on a desktop, that doing a sync from genesis became completely impractical).

**Comment by bobsummerwill** [comment]
Were any binaries released since v1.3.0 "Homecoming", guys?

https://github.com/bobsummerwill/cpp-ethereum/releases/tag/v1.3.0

Or maybe just Docker images?

Any versioned releases?   Even just as source code?

Planning on a versioned release soon?

**Comment by bobsummerwill** [comment]
I remember now that we didn't do Homebrew or PPA builds for v1.3.0 - only ZIPs, because of the time pressures of the DAO fork.

The ZIP for Ubuntu was useless (because .so has hard-coded paths so is not relocatable), but the Windows and MacOS binaries worked.

**Comment by bobsummerwill** [comment]
Was all effort on PPAs and Homebrew dropped when I left the Foundation?   And all focus put on Docker builds?

I think that was rational.

**Comment by bobsummerwill** [comment]
Gotta get my Purism Librem 15 booted up again too, and get the build working on PureOS :-)

**Comment by yep** [comment]
Sorry, I don't think I will have time to look into this pull request.

**Comment by bobsummerwill** [comment]
No problem, @yep!
Maybe somebody else will pop up who cares about iOS.

**Pull request closed without merging**
